### ISSUE TITLE
【css动效】实现一个按钮悬浮border动画

### ISSUE THREAD

**Issue by Censwin** [Censwin/relearnjs#2]
![test1](https://user-images.githubusercontent.com/49546849/124093997-ef4bdb00-da8a-11eb-9640-503a8d7c6840.gif)
[codesandbox](https://codesandbox.io/s/btn-loading-effect-9t5jl?file=/src/styles.scss:122-2239)
```html
<div className="btn-wrapper">
    <div className="rectangle">rectangle</div>
    <div className="circle">circle</div>
  </div>
```

```css
.btn-wrapper {
  &>div {
    &::before,&::after {
      content: "";
      position: absolute;
      box-sizing: border-box;
      width: 0;
      height: 0;
      border: 3px solid transparent; // width 为0会显示border将其设为透明
    }
  }
}
// 正方形按钮
.rectangle {
  position: relative;
  width: 150px;
  height: 45px;
  line-height: 45px;
  text-align: center;
  box-shadow: 0 0 0 3px #ddd inset;
  border-radius: 5px;
  &::before {
    left: 0;
    top: 0;
    border-radius: 5px;
  }
  &::after {
    right: 0;
    bottom: 0;
    border-radius: 5px;
  }
  &:hover {
    cursor: pointer;
    transition: color 1s;
    color:tomato;
    &::before  {
      width: 0;
      height: 0;
      transition: height .25s linear 0s,
      width .25s linear .25s,
      border-bottom-color;
      width: 150px;
      height: 45px;
      border-left: 3px solid tomato;
      border-bottom: 3px solid tomato;
    }
    &::after {
      width: 0;
      height: 0;
      transition: height .25s linear .5s,
      width .25s linear .75s,
      border-right-color 2.5s
      ,border-top-color 3s;
      width: 150px;
      height: 45px;
      border-top: 3px solid tomato;
      border-right: 3px solid tomato;
    }
  }
}
// 圆形按钮
.circle {
  margin-top: 15px;
  width: 100px;
  height: 100px;
  border-radius: 50%;
  text-align: center;
  line-height: 100px;
  box-shadow: 0 0 0 3px #ddd inset;
  position: relative;
  border: 3px solid transparent;
  &::before,&::after{
      border-radius: 50%; 
      position: absolute;
      left: 0;
      top: 0;
  }
  &:hover {
    cursor: pointer;
    transition: color 1s;
    color: tomato;
    &::before {
      width: 100px;
      height: 100px;
      border-color: tomato;
      transition: border-top-color .25s linear,
      border-right-color .25s linear,
      border-bottom-color .25s linear,
      border-left-color .25s linear;
      transition-delay: 0s, .25s, .5s, .75s;
    }
    &::after { // 旋转过度效果
      width: 100px;
      height: 100px;
      border-top: 3px solid tomato;
      transition: transform .99s linear 0s;
      transform: rotate(270deg);
    }
  }
}
```
